INSERT INTO PROJECT                                                     
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)      
VALUES('AD3110','GENERAL AD SYSTEMS','D21','000070',6.00,'1982-01-01'   
              ,'1983-02-01','AD3100');                                  
INSERT INTO PROJECT                                                     
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)      
VALUES('AD3111','PAYROLL PROGRAMMING','D21','000230',2.00,'1982-01-01'  
              ,'1983-02-01','AD3110');                                  
INSERT INTO PROJECT                                                     
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)      
VALUES('AD3112','PERSONAL PROGRAMMING','D21','000250',1.00,'1982-01-01' 
              ,'1983-02-01','AD3110');                                  
INSERT INTO PROJECT                                                     
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)      
VALUES('AD3113','ACCOUNT PROGRAMMING','D21','000270',2.00,'1982-01-01'  
              ,'1983-02-01','AD3110');                                  
INSERT INTO PROJECT                                                 
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)  
VALUES('IF1000','QUERY SERVICES','C01','000030',2.00,'1982-01-01'   
              ,'1983-02-01',NULL);                                  
INSERT INTO PROJECT                                                 
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,PRENDATE,MAJPROJ)  
VALUES('IF2000','USER EDUCATION','C01','000030',1.00,'1982-01-01'   
              ,'1983-02-01',NULL);                                  
INSERT INTO PROJECT                                                 
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,                   
PRENDATE,MAJPROJ)                                                   
VALUES('MA2100','WELD LINE AUTOMATION','D01','000010',12.00,        
'1982-01-01','1983-02-01',NULL);                                    
INSERT INTO PROJECT                                                 
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,                   
PRENDATE,MAJPROJ)                                                   
VALUES('MA2110','W L PROGRAMMING','D11','000060',9.00,              
'1982-01-01','1983-02-01','MA2110');                            
INSERT INTO PROJECT                                             
(PROJNO,PROJNAME,DEPTNO,RESPEMP,PRSTAFF,PRSTDATE,               
PRENDATE,MAJPROJ)                                               
VALUES('MA2111','W L PROGRAM DESIGN','D11','000220',2.00,       
'1982-01-01','1982-12-01','MA2110');                            
