INSERT INTO DEPARTMENT                                             
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                          
VALUES('A00','SPIFFY COMPUTER SERVICES DIV','000020','A00',NULL);  
INSERT INTO DEPARTMENT                                             
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                          
VALUES('B01','PLANNING','000030','A00',NULL);                      
INSERT INTO DEPARTMENT                                             
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                          
VALUES('C01','INFORMATION CENTER','000040','A00',NULL);            
INSERT INTO DEPARTMENT                                             
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                          
VALUES('D01','DEVELOPMENT CENTER','000050','D01',NULL);            
 INSERT INTO DEPARTMENT                                            
 (DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                         
 VALUES('D11','MANUFACTURING SYSTEMS','000060','D01',NULL);        
 INSERT INTO DEPARTMENT                                            
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                        
VALUES('D21','ADMINISTRATING SYSTEMS','000070','A00',NULL);      
INSERT INTO DEPARTMENT                                           
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                        
VALUES('E01','SUPPORT SERVICES','000080','A00',NULL);            
INSERT INTO DEPARTMENT                                           
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                        
VALUES('E11','OPERATIONS','000090','E01',NULL);                  
INSERT INTO DEPARTMENT                                           
(DEPTNO,DEPTNAME,MGRNO,ADMRDEPT,LOCATION)                        
VALUES('E21','SOFTWARE SUPPORT','000100','EO1',NULL);            
